config/routes.rb
Zhuke::Application.routes.draw do
  #get \"users\/show\"

  root :to => "home#index"

  devise_for :users, :controllers => {:registrations => "registrations",
                                      #:sessions => "sessions",
                                      :password      => "devise/passwords",
                                      :invitations   => "invitations",
                                      :omniauth_callbacks => "users/omniauth_callbacks" } do
    get "/register", :to => "devise/registrations#new" 
    get "/login", :to => "devise/sessions#new" 
    get "/logout", :to => "devise/sessions#destroy"
  end
  
  # omniauth client stuff
  match '/auth/:provider/callback', :to => 'users#auth_callback'
  match '/auth/failure', :to => 'users#auth_failure'
    
  resources :users do
    member do
      get "following"
      post "follow"
      get "followers"
      post "unfollow"
    end
  end  
  
  resources :recipes do
    resources :comments, :controller => "comments"
    member do
      post "share"
    end
  end
  
  # Show all the shared by me
  resources :shareds
  
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :content

  belongs_to :user
  embedded_in :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  # GET /comments
  # GET /comments.xml
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.xml
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  def new
    @post = Post.find(params[:recipe_id])
    @comment = @post.comments.build
  end

  def edit
  end

  # POST /comments
  # POST /comments.xml
  def create
    @post = Post.find(params[:recipe_id])
    @comment = @post.comments.build(params[:comment])
    @comment.user_id = current_user.id
    
    if @comment.save
      respond_to do |format|
        format.html { redirect_to(@recipe, :notice => 'Comment was successfully created.') }
        format.js
      end
    else
      render :new
    end
  end

  # PUT /comments/1
  # PUT /comments/1.xml
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to(@comment, :notice => 'Comment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.xml
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to(comments_url) }
      format.xml  { head :ok }
    end
  end
  
private
  def find_text
    @text = Recipe.find(params[:text_id])
  end

  def find_or_build_comment
    @comment = params[:id] ? @text.comments.find(params[:id]) : @text.comments.build(params[:comment])
  end
end

app/views/comments/_form.html.haml
= simple_form_for [@post, @comment] do |f|
  = @post.title
  %br
  = @post.id
  %br
  .field
    = f.input :content, :as => :text, :style => "width:420px; height:80px;"
    
  .actions
    = f.button :submit

app/views/comments/create.js.haml
:plain
  alert("d");

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', comments_path

app/views/comments/index.html.haml
%h1 Listing comments

%table
  %tr
    %th Content
    %th
    %th
    %th

  - @comments.each do |comment|
    %tr
      %td= comment.con

%br

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

app/views/comments/show.html.haml
%p#notice= notice

%p
  %b Post:
  = @comment.post

= link_to 'Edit', edit_comment_path(@comment)
\|
= link_to 'Back', comments_path