config/routes.rb
Zhuke::Application.routes.draw do
  #get \"users\/show\"

  root :to => "home#index"

  devise_for :users, :controllers => {:registrations => "registrations",
                                      #:sessions => "sessions",
                                      :password      => "devise/passwords",
                                      :invitations   => "invitations",
                                      :omniauth_callbacks => "users/omniauth_callbacks" } do
    get "/register", :to => "devise/registrations#new" 
    get "/login", :to => "devise/sessions#new" 
    get "/logout", :to => "devise/sessions#destroy"
  end
  
  # omniauth client stuff
  match '/auth/:provider/callback', :to => 'users#auth_callback'
  match '/auth/failure', :to => 'users#auth_failure'
    
  resources :users do
    member do
      get "following"
      post "follow"
      get "followers"
      post "unfollow"
    end
  end  
  
  resources :recipes do
    resources :comments, :controller => "comments"
    member do
      post "share"
    end
  end
  
  # Show all the shared by me
  resources :shareds
  
end

app/models/recipe.rb
class Recipe < Post
  field :title
  field :description
  field :picture
  field :material
  field :step
  #field :status
  #field :public
  #field :slug
  
  #mount_uploader :picture, RecipeUploader
    
end

app/controllers/recipes_controller.rb
class RecipesController < PostsController
  
  def index
    @recipes = Recipe.all
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(params[:recipe])
    @recipe.user_id = current_user.id
    
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to(@recipe, :notice => 'recipe was successfully created.') }
        format.xml  { render :xml => @recipe, :status => :created, :location => @recipe }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @recipe.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def show
    @recipe = Recipe.find(params[:id])
    @comments = @recipe.comments
  end
  
  def edit
    @recipe = Recipe.find(params[:id])
  end
  
  def update
    @recipe = Recipe.find(params[:id])
    
    @recipe.update_attributes(params[:recipe])
  end
  
  def destory
    @recipe = Recipe.find(params[:id])
    @recipe.destory
  end
  
  def share
    @shared = Shared.new(params[:shared])
    #@content = Content.find(params[:id])
    #@shared.content_id = params[:id]
    
    @post = Post.find(params[:id])
    @shared.post = @post
    @shared.user_id = current_user.id
    
    respond_to do |format|
      if @shared.save
        format.html
        format.js
      else
        format.html
        format.xml
      end
    end
  end
end

app/views/recipes/_comment.html.haml
= simple_form_for( [@recipe, Comment.new], :remote => true, :html => {"data-type" => "json"} ) do |f|
  .field
    = f.input :content, :as => :text
    
  .actions
    = f.button :submit

app/views/recipes/_form.html.haml
= simple_form_for @recipe do |f|

  = f.input :title
  = f.input :description, :as => :text
  = f.input :picture
  = f.input :material, :as => :text
  = f.input :step, :as => :text
  
  = f.button :submit

app/views/recipes/_share.html.haml
= simple_form_for( :shared, :url => share_recipe_path(@recipe), :remote => true ) do |f|
  .field
    = f.input :content, :as => :text
    
  .actions
    = f.button :submit

app/views/recipes/edit.html.haml
%h1 New Recipe

= render 'form'

= link_to 'Back', recipes_path

app/views/recipes/index.html.haml
%h1 Listing Recipes

%table
  %tr
    %th title
    %th Content
    
  - @recipes.each do |recipe|
    %tr
      %td 
        = link_to recipe.title, text
      %td
        = recipe.content
      
= link_to 'New Recipe', new_recipe_path

app/views/recipes/new.html.haml
%h1 New Recipe1

= render 'form'

= link_to 'Back', recipes_path

app/views/recipes/show.html.haml
.span-15.append-2
  #stream_container
    %h1
      = (@recipe.title).html_safe
  
    %h5
      = image_tag( @recipe.picture.url )

    = (@recipe.description).html_safe

    .recipe_info
      .ll
        .recipe-star-block
        .recipe-stats 318浏览
        .uncollect 取消
        .uncollect + 收藏
     
    Up load my recipe !!! --------------------------------   shared to Weibo, Douban
    %br
    %br
    %hr
    = (@recipe.material).html_safe
    %br
    %hr
    %br
    = (@recipe.step).html_safe

    %br
    %br
    = link_to 'Edit Recipe', edit_recipe_path(@recipe)

    %br
    %br

    %h5 Comments
    %table
      %tr
      - @comments.each do |comment|
        %tr
          %td
            = comment.user.name
          %td 
            = comment.content

    = render"comment"

    = render "share"
    
/ Show the right sidebar
.span-7.last{:style => "height:400px;"}
  = @recipe.user.name